"""Oracle protocol for skill validation.

Today, a skill is validated by:
  1. Checking it produces the original episode's stored solution.
  2. Asking the same Gemma model "is this answer correct? YES/NO".
  3. Running adversarial stress tests *whose ground-truth labels were
     generated by the same model*.

This is a leaky validation signal — the same model writes both the
skill and the "ground truth", so systematic errors are not caught.

The right fix is to plug an *external* oracle:
  * SymPy / NumPy for math problems (numerical equality up to tolerance);
  * pytest-style hidden testcases for code generation (HumanEval+, MBPP+);
  * unit-tests authored by the user for domain-specific tasks.

This module defines a minimal protocol so callers (the sleep-phase skill
extractor) can be retrofitted to use a real oracle without changing the
skill-generation API. A working SymPy-based example is included.
"""

from __future__ import annotations

import math
import re
from typing import Any, Callable, List, Optional, Protocol, Tuple


class Oracle(Protocol):
    """A function that decides whether a (query, candidate_answer) pair is correct.

    Returns ``(correct, info)`` where ``info`` is a free-form diagnostic
    string the validator can include in its repair prompt.
    """

    def __call__(self, query: str, candidate_answer: str) -> Tuple[bool, str]: ...


# ---------------------------------------------------------------------------
# Built-in oracles
# ---------------------------------------------------------------------------


def numeric_set_oracle(
    expected_numbers: List[float],
    *,
    rel_tol: float = 1e-6,
    abs_tol: float = 1e-9,
) -> Oracle:
    """Oracle for math/sequence tasks.

    Extracts all numbers from the candidate answer and checks that every
    ``expected_number`` is matched by at least one extracted number
    within tolerance.
    """
    def _oracle(query: str, candidate_answer: str) -> Tuple[bool, str]:
        nums = [
            float(m)
            for m in re.findall(r"-?\d+\.?\d*", candidate_answer)
        ]
        if not nums:
            return False, "no numeric values found in candidate answer"
        missing = []
        for expected in expected_numbers:
            if not any(
                math.isclose(n, expected, rel_tol=rel_tol, abs_tol=abs_tol)
                for n in nums
            ):
                missing.append(expected)
        if missing:
            return False, f"missing expected numbers: {missing}"
        return True, "ok"

    return _oracle


def string_contains_oracle(must_contain: List[str]) -> Oracle:
    """Oracle for extraction tasks: candidate must contain each substring."""
    def _oracle(query: str, candidate_answer: str) -> Tuple[bool, str]:
        missing = [s for s in must_contain if s not in candidate_answer]
        if missing:
            return False, f"missing substrings: {missing}"
        return True, "ok"

    return _oracle


def python_assert_oracle(
    test_code: str, *, timeout_seconds: float = 5.0
) -> Oracle:
    """Oracle that runs `assert` statements against the candidate.

    The test code receives the candidate answer as the variable ``answer``.
    Use this for HumanEval/MBPP-style tasks where you have hidden tests.

    NOTE: like skill execution, this runs *generated* test_code through
    the AST sandbox. For *trusted* tests authored by the user, you can
    bypass the sandbox by passing them directly as plain Python.
    """
    from .sandbox import safe_load_module, SecurityError

    template = (
        "def _check(answer):\n"
        + "\n".join("    " + line for line in test_code.splitlines())
        + "\n"
    )

    def _oracle(query: str, candidate_answer: str) -> Tuple[bool, str]:
        try:
            ns = safe_load_module(template)
            ns["_check"](candidate_answer)
            return True, "ok"
        except SecurityError as e:
            return False, f"oracle test code rejected by sandbox: {e}"
        except AssertionError as e:
            return False, f"assertion failed: {e}"
        except Exception as e:  # noqa: BLE001
            return False, f"oracle test crashed: {type(e).__name__}: {e}"

    return _oracle


def llm_yes_no_oracle(judge_fn: Callable[[str], str]) -> Oracle:
    """Fallback oracle wrapping an LLM YES/NO judge.

    DOCUMENTED LIMITATION: not an independent oracle — when the judge
    LLM is the same family that wrote the skill, this signal is
    systematically biased. Use only as a last resort.
    """
    def _oracle(query: str, candidate_answer: str) -> Tuple[bool, str]:
        prompt = (
            "Task: " + query + "\n"
            "Proposed answer: " + candidate_answer + "\n\n"
            "Is the proposed answer correct? Reply with exactly YES or NO."
        )
        verdict = judge_fn(prompt).strip().upper()
        if "YES" in verdict and "NO" not in verdict.split()[0:1]:
            return True, "llm verdict: yes"
        return False, f"llm verdict: {verdict[:40]}"

    return _oracle


__all__ = [
    "Oracle",
    "numeric_set_oracle",
    "string_contains_oracle",
    "python_assert_oracle",
    "llm_yes_no_oracle",
]
