"""Oracle protocol for skill validation.

Today, a skill is validated by:
  1. Checking it produces the original episode's stored solution.
  2. Asking the same Gemma model "is this answer correct? YES/NO".
  3. Running adversarial stress tests *whose ground-truth labels were
     generated by the same model*.

This is a leaky validation signal — the same model writes both the
skill and the "ground truth", so systematic errors are not caught.

The right fix is to plug an *external* oracle:
  * SymPy / NumPy for math problems (numerical equality up to tolerance);
  * pytest-style hidden testcases for code generation (HumanEval+, MBPP+);
  * unit-tests authored by the user for domain-specific tasks.

This module defines a minimal protocol so callers (the sleep-phase skill
extractor) can be retrofitted to use a real oracle without changing the
skill-generation API. A working SymPy-based example is included.
"""

from __future__ import annotations

import math
import re
from typing import Any, Callable, List, Optional, Protocol, Tuple


class Oracle(Protocol):
    """A function that decides whether a (query, candidate_answer) pair is correct.

    Returns ``(correct, info)`` where ``info`` is a free-form diagnostic
    string the validator can include in its repair prompt.
    """

    def __call__(self, query: str, candidate_answer: str) -> Tuple[bool, str]: ...


# ---------------------------------------------------------------------------
# Built-in oracles
# ---------------------------------------------------------------------------


def numeric_set_oracle(
    expected_numbers: List[float],
    *,
    rel_tol: float = 1e-6,
    abs_tol: float = 1e-9,
) -> Oracle:
    """Oracle for math/sequence tasks.

    Extracts all numbers from the candidate answer and checks that every
    ``expected_number`` is matched by at least one extracted number
    within tolerance.
    """
    def _oracle(query: str, candidate_answer: str) -> Tuple[bool, str]:
        nums = [
            float(m)
            for m in re.findall(r"-?\d+\.?\d*", candidate_answer)
        ]
        if not nums:
            return False, "no numeric values found in candidate answer"
        missing = []
        for expected in expected_numbers:
            if not any(
                math.isclose(n, expected, rel_tol=rel_tol, abs_tol=abs_tol)
                for n in nums
            ):
                missing.append(expected)
        if missing:
            return False, f"missing expected numbers: {missing}"
        return True, "ok"

    return _oracle


def string_contains_oracle(must_contain: List[str]) -> Oracle:
    """Oracle for extraction tasks: candidate must contain each substring."""
    def _oracle(query: str, candidate_answer: str) -> Tuple[bool, str]:
        missing = [s for s in must_contain if s not in candidate_answer]
        if missing:
            return False, f"missing substrings: {missing}"
        return True, "ok"

    return _oracle


def python_assert_oracle(
    test_code: str, *, timeout_seconds: float = 5.0
) -> Oracle:
    """Oracle that runs `assert` statements against the candidate.

    The test code receives the candidate answer as the variable ``answer``.
    Use this for HumanEval/MBPP-style tasks where you have hidden tests.

    NOTE: like skill execution, this runs *generated* test_code through
    the AST sandbox. For *trusted* tests authored by the user, you can
    bypass the sandbox by passing them directly as plain Python.
    """
    from .sandbox import safe_load_module, SecurityError

    template = (
        "def _check(answer):\n"
        + "\n".join("    " + line for line in test_code.splitlines())
        + "\n"
    )

    def _oracle(query: str, candidate_answer: str) -> Tuple[bool, str]:
        try:
            ns = safe_load_module(template)
            ns["_check"](candidate_answer)
            return True, "ok"
        except SecurityError as e:
            return False, f"oracle test code rejected by sandbox: {e}"
        except AssertionError as e:
            return False, f"assertion failed: {e}"
        except Exception as e:  # noqa: BLE001
            return False, f"oracle test crashed: {type(e).__name__}: {e}"

    return _oracle


def llm_yes_no_oracle(judge_fn: Callable[[str], str]) -> Oracle:
    """Fallback oracle wrapping an LLM YES/NO judge.

    DOCUMENTED LIMITATION: not an independent oracle — when the judge
    LLM is the same family that wrote the skill, this signal is
    systematically biased. Use only as a last resort.
    """
    def _oracle(query: str, candidate_answer: str) -> Tuple[bool, str]:
        prompt = (
            "Task: " + query + "\n"
            "Proposed answer: " + candidate_answer + "\n\n"
            "Is the proposed answer correct? Reply with exactly YES or NO."
        )
        verdict = judge_fn(prompt).strip().upper()
        if "YES" in verdict and "NO" not in verdict.split()[0:1]:
            return True, "llm verdict: yes"
        return False, f"llm verdict: {verdict[:40]}"

    return _oracle


def cached_episode_oracle(
    expected_solution: str,
    *,
    rel_tol: float = 1e-6,
    abs_tol: float = 1e-9,
) -> Oracle:
    """Strict deterministic oracle backed by a cached, solved episode.

    This is the ground-truth check that the paper's "compile-from-replay"
    workflow actually requires: a generated skill must reproduce the
    *exact* output of a previously-solved episode, not just share enough
    string fragments with it.

    Accept conditions, in order:

      1. Normalized exact-string match (surrounding whitespace stripped,
         internal whitespace collapsed). If the candidate ``startswith
         "Error"`` we reject regardless.
      2. If the expected solution contains numeric tokens:
         a. The candidate is not an error string.
         b. Every expected number is matched within tolerance by some
            number extracted from the candidate.
         c. The candidate does not introduce *additional* numeric tokens
            that are absent from the expected solution. This is the
            "no extra hallucinated numbers" gate that distinguishes a
            correct answer ("7") from a verbose wrong one ("answer: 7
            because 1+2+3+4 = 10").
      3. Otherwise reject.

    No LLM judge, no partial credit, no 20%-coverage heuristic. Use this
    as the default fallback in :func:`nare.llm._validate_skill` when
    validating a compiled skill against a previously-solved episode
    whose stored solution is the verified ground truth.
    """
    raw_expected = (expected_solution or "").strip()
    expected_normalized = re.sub(r"\s+", " ", raw_expected).lower()
    expected_nums = [
        float(m) for m in re.findall(r"-?\d+\.?\d*", raw_expected)
    ]

    def _oracle(query: str, candidate_answer: str) -> Tuple[bool, str]:
        cand = (candidate_answer or "").strip()
        if cand.startswith("Error"):
            return False, f"candidate is an error string: {cand[:60]}"
        if raw_expected == "" or raw_expected == "N/A":
            # Episode without a verified solution cannot ground-truth a
            # skill; treat any non-error output as inconclusive
            # (rejected) so we never promote on missing ground truth.
            return False, "cached episode has no verified solution"

        cand_normalized = re.sub(r"\s+", " ", cand).lower()
        if cand_normalized == expected_normalized:
            return True, "exact normalized string match"

        if expected_nums:
            cand_nums = [
                float(m) for m in re.findall(r"-?\d+\.?\d*", cand)
            ]
            if not cand_nums:
                return False, "expected numeric answer, candidate has no numbers"

            # Every expected number must appear in the candidate.
            for expected in expected_nums:
                if not any(
                    math.isclose(n, expected, rel_tol=rel_tol, abs_tol=abs_tol)
                    for n in cand_nums
                ):
                    return False, (
                        f"missing expected number {expected} "
                        f"(got {cand_nums})"
                    )

            # No extra unrelated numbers — every candidate number must
            # also be in the expected set. This catches verbose wrong
            # answers that happen to contain the right number.
            for got in cand_nums:
                if not any(
                    math.isclose(got, e, rel_tol=rel_tol, abs_tol=abs_tol)
                    for e in expected_nums
                ):
                    return False, (
                        f"extra unrelated number {got} "
                        f"(expected only {expected_nums})"
                    )

            return True, "strict numeric set match"

        return False, (
            f"non-numeric expected '{raw_expected[:40]}' but no string match "
            f"with candidate '{cand[:40]}'"
        )

    return _oracle


def heuristic_overlap_oracle(expected_solution: str) -> Oracle:
    """Default oracle reproducing the legacy string/numeric-overlap check.

    This is what ``_validate_skill`` used inline before oracles were
    pluggable: a candidate is "correct" if it matches the expected
    solution exactly, contains it, is contained by it, OR shares
    enough numeric tokens with it (>= 20% coverage of expected numbers).

    It is **a heuristic, not a real ground-truth check**. Use it as the
    fallback when no stricter oracle is available; prefer
    :func:`numeric_set_oracle` or :func:`python_assert_oracle` whenever
    you can reduce the task to one of those forms.
    """
    expected = (expected_solution or "").strip()

    def _oracle(query: str, candidate_answer: str) -> Tuple[bool, str]:
        cand = (candidate_answer or "").strip()
        if expected == "" or expected == "N/A":
            if cand and not cand.startswith("Error"):
                return True, "no expected solution; non-error output accepted"
            return False, "no expected solution and candidate is empty/error"

        if cand == expected or cand in expected or expected in cand:
            return True, "string match"

        cand_nums = set(re.findall(r"-?\d+\.?\d*", cand))
        exp_nums = set(re.findall(r"-?\d+\.?\d*", expected))
        if cand_nums and exp_nums:
            overlap = cand_nums & exp_nums
            coverage = len(overlap) / len(exp_nums)
            if coverage >= 0.2 or (
                len(cand_nums) == 1 and cand_nums.issubset(exp_nums)
            ):
                return True, f"numeric overlap {coverage:.0%}"
            return False, (
                f"numeric mismatch: expected {sorted(exp_nums)}, "
                f"got {sorted(cand_nums)}"
            )

        if cand and not cand.startswith("Error"):
            # Partial credit: legacy behaviour gave 0.5 here. We surface
            # it via info so the caller can decide whether to count it.
            return False, "non-error output but no string/numeric match"

        return False, f"expected '{expected[:40]}' got '{cand[:40]}'"

    return _oracle


def test_execution_oracle(
    repo_manager,
    task_id: str,
    test_command: str,
    timeout: int = 300
) -> Oracle:
    """Oracle that applies solution and runs tests in real repository.

    Args:
        repo_manager: RepoManager instance
        task_id: Task ID
        test_command: Command to run tests (e.g., "pytest path/to/test.py")
        timeout: Test timeout in seconds

    Returns:
        Oracle function that validates by running tests
    """
    def _oracle(query: str, candidate_answer: str) -> Tuple[bool, str]:
        # Apply solution to repository
        success, error = repo_manager.apply_solution(task_id, candidate_answer)

        if not success:
            return False, f"Failed to apply solution: {error}"

        # Run tests
        passed, output = repo_manager.run_tests(task_id, test_command, timeout)

        if passed:
            return True, "Tests passed"
        else:
            # Return first 500 chars of error output
            return False, f"Tests failed: {output[:500]}"

    return _oracle


def build_oracle_from_spec(spec: dict) -> Oracle:
    """Materialize an Oracle from a JSON-serializable specification.

    Episodes can carry an ``oracle_spec`` field on disk (so they survive
    save/load). Recognized shapes:

      * ``{"type": "numeric_set", "expected": [42, 3.14], "rel_tol": 1e-6}``
      * ``{"type": "string_contains", "must_contain": ["foo", "bar"]}``
      * ``{"type": "python_assert", "code": "assert int(answer) == 5"}``
      * ``{"type": "heuristic_overlap", "expected_solution": "..."}``
      * ``{"type": "test_execution", "repo_manager": <obj>, "task_id": "...", "test_command": "pytest ..."}``

    Unknown ``type`` values raise ``ValueError`` so callers can detect
    misconfiguration rather than silently fall back to a weaker oracle.
    """
    kind = spec.get("type")
    if kind == "numeric_set":
        return numeric_set_oracle(
            list(spec.get("expected", [])),
            rel_tol=spec.get("rel_tol", 1e-6),
            abs_tol=spec.get("abs_tol", 1e-9),
        )
    if kind == "string_contains":
        return string_contains_oracle(list(spec.get("must_contain", [])))
    if kind == "python_assert":
        code = spec.get("code", "")
        if not isinstance(code, str) or not code.strip():
            raise ValueError("python_assert oracle requires non-empty 'code'")
        return python_assert_oracle(code)
    if kind == "heuristic_overlap":
        return heuristic_overlap_oracle(spec.get("expected_solution", ""))
    if kind == "cached_episode":
        return cached_episode_oracle(
            spec.get("expected_solution", ""),
            rel_tol=spec.get("rel_tol", 1e-6),
            abs_tol=spec.get("abs_tol", 1e-9),
        )
    if kind == "test_execution":
        repo_manager = spec.get("repo_manager")
        task_id = spec.get("task_id")
        test_command = spec.get("test_command")
        timeout = spec.get("timeout", 300)
        if not repo_manager or not task_id or not test_command:
            raise ValueError("test_execution oracle requires repo_manager, task_id, and test_command")
        return test_execution_oracle(repo_manager, task_id, test_command, timeout)
    raise ValueError(f"Unknown oracle spec type: {kind!r}")


__all__ = [
    "Oracle",
    "numeric_set_oracle",
    "string_contains_oracle",
    "python_assert_oracle",
    "llm_yes_no_oracle",
    "heuristic_overlap_oracle",
    "cached_episode_oracle",
    "test_execution_oracle",
    "build_oracle_from_spec",
]
